In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from difflib import get_close_matches

In [99]:
df = pd.read_csv(r'IMDB_Dataset.csv', encoding='latin1', sep=None, engine='python')

In [45]:
pd.set_option('display.max_rows', None)

In [46]:
df

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Unnamed: 8,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"
5,tt0167260,The Lord of the Rings: The Return of the King,22 Feb 04,"Action, Adventure, Drama",201,New Zealand,PG-13,Peter Jackson,NaN,$ 1142271098,1.604.280,08.9
6,tt0108052,Schindler's List,1994-03-11,"Biography, Drama, History",Nan,USA,R,Steven Spielberg,NaN,$ 322287794,1.183.248,8.9
7,tt0050083,12 Angry Men,1957-09-04,"Crime, Drama",96,USA,Not Rated,Sidney Lumet,NaN,$ 576,668.473,8.9
8,tt1375666,Inception,2010-09-24,"Action, Adventure, Sci-Fi",148,USA,PG-13,Christopher Nolan,NaN,$ 869784991,2.002.816,8..8
9,tt0137523,Fight Club,10-29-99,Drama,Inf,UK,R,David Fincher,NaN,$ 101218804,1.807.440,8.8
10,tt0109830,Forrest Gump,1994-10-06,"Drama, Romance",142,USA,PG-13,Robert Zemeckis,NaN,$ 678229452,1.755.490,8:8
11,tt0120737,The Lord of the Rings: The Fellowship of the Ring,2002-01-18,"Action, Adventure, Drama",178c,New Zesland,PG-13,Peter Jackson,NaN,$ 887934303,1.619.920,8.8
12,tt0060196,"Il buono, il brutto, il cattivo",23rd December of 1966,Western,161,Italy,Approved,Sergio Leone,NaN,$ 25252481,672.499,8.8
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,tt0133093,The Matrix,1999-05-07,"Action, Sci-Fi",NaN,USA,R,"Lana Wachowski, Lilly Wachowski",NaN,$ 465718588,1.632.315,++8.7
15,tt0167261,The Lord of the Rings: The Two Towers,01/16-03,"Action, Adventure, Drama",179,New Zeland,PG-13,Peter Jackson,NaN,$ 951227416,1.449.778,8.7.
16,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980-09-19,"Action, Adventure, Fantasy",Not Applicable,USA,PG,Irvin Kershner,NaN,$ 549265501,1.132.073,"8,7e-0"
17,tt0099685,Goodfellas,1990-09-20,"Biography, Crime, Drama",146,USA,R,Martin Scorsese,NaN,$ 46879633,991.505,8.7
18,tt0073486,One Flew Over the Cuckoo's Nest,18/11/1976,Drama,-,USA,R,Milos Forman,NaN,$ 108997629,891.071,8.7
19,tt0816692,Interstellar,2014-11-06,"Adventure, Drama, Sci-Fi",169,USA,PG-13,Christopher Nolan,NaN,$ 696742056,1.449.256,8.6
20,tt0114369,Se7en,1995-12-15,"Crime, Drama, Mystery",127,USA,R,David Fincher,NaN,$ 327333559,1.402.015,8.6
21,tt0102926,The Silence of the Lambs,1991-03-05,"Crime, Drama, Thriller",118,USA,R,Jonathan Demme,NaN,$ 272753884,1.234.134,"8,6"
22,tt0076759,Star Wars,1977-10-20,"Action, Adventure, Fantasy",121,USA,PG,George Lucas,NaN,$ 775768912,1.204.107,8.6
23,tt0120815,Saving Private Ryan,1998-10-30,"Drama, War",169,USA,R,Steven Spielberg,NaN,$ 482349603,1.203.825,8.6
24,tt0120689,The Green Mile,2000-10-03,"Crime, Drama, Fantasy",189,US.,R,Frank Darabont,NaN,$ 286801374,1.112.336,8.6
25,tt0317248,Cidade de Deus,2003-05-09,"Crime, Drama",130,Brazil,R,"Fernando Meirelles, KÃ¡tia Lund",NaN,$ 30680793,685.856,8.6
26,tt0245429,Sen to Chihiro no kamikakushi,2003-04-18,"Animation, Adventure, Family",125,Japan,PG,Hayao Miyazaki,NaN,$ 355467056,626.693,8.6
27,tt0118799,La vita B9 bella,1997-12-20,"Comedy, Drama, Romance",116,Italy1,NaN,Roberto Benigni,NaN,$ 230098753,605.648,8.6
28,tt6751668,Gisaengchung,2019-11-07,"Comedy, Drama, Thriller",132,South Korea,NaN,Bong Joon Ho,NaN,$ 257604912,470.931,8.6
29,tt0038650,It's a Wonderful Life,1948-03-11,"Drama, Family, Fantasy",130,USA,PG,Frank Capra,NaN,$ 6130720,388.310,8.6
30,tt0047478,Shichinin no samurai,1955-08-19,"Action, Adventure, Drama",207,Japan,Unrated,Akira Kurosawa,NaN,$ 322773,307.958,8.6
31,tt0172495,Gladiator,2000-05-19,"Action, Adventure, Drama",155,USA,R,Ridley Scott,NaN,$ 465361176,1.308.193,8.5
32,tt0407887,The Departed,2006-10-27,"Crime, Drama, Thriller",151,USA,R,Martin Scorsese,NaN,$ 291465034,1.159.703,8.5
33,tt0482571,The Prestige,2006-12-22,"Drama, Mystery, Sci-Fi",130,UK,PG-13,Christopher Nolan,NaN,$ 109676311,1.155.723,8.5
34,tt0088763,Back to the Future,1985-10-18,"Adventure, Comedy, Sci-Fi",116,USA,PG,Robert Zemeckis,NaN,$ 388774684,1.027.330,8.5
35,tt0120586,American History X,1999-08-27,Drama,119,USA,R,Tony Kaye,NaN,$ 23875127,1.014.218,8.5
36,tt0110413,LÃ©on,1995-04-07,"Action, Crime, Drama",110,France,NaN,Luc Besson,NaN,$ 19552639,1.007.598,8.5
37,tt0103064,Terminator 2: Judgment Day,1991-12-19,"Action, Sci-Fi",137,USA,R,James Cameron,NaN,$ 520884847,974.970,8.4
38,tt0114814,The Usual Suspects,1995-11-30,"Crime, Mystery, Thriller",106,USA,R,Bryan Singer,NaN,$ 23341568,968.947,8.4
39,tt0110357,The Lion King,1994-11-25,"Animation, Adventure, Drama",88,USA,G,"Roger Allers, Rob Minkoff",NaN,$ 968511805,917.248,8.4
40,tt7286456,Joker,2019-10-03,"Crime, Drama, Thriller",122,USA,NaN,Todd Phillips,NaN,$ 1074251311,855.097,8.4
41,tt1675434,Intouchables,2012-02-24,"Biography, Comedy, Drama",112,France,NaN,"Olivier Nakache, Ãric Toledano",NaN,$ 426588510,736.691,8.4
42,tt0253474,The Pianist,2002-10-25,"Biography, Drama, Music",150,UK,R,Roman Polanski,NaN,$ 120072577,707.942,8.4
43,tt2582802,Whiplash,2015-02-12,"Drama, Music",106,USA,R,Damien Chazelle,NaN,$ 48983260,690.732,8.4
44,tt0054215,Psycho,1960-10-28,"Horror, Mystery, Thriller",109,USA,R,Alfred Hitchcock,NaN,$ 32008644,586.765,8.3
45,tt0034583,Casablanca,21-11-46,"Drama, Romance, War",102,USA,PG,Michael Curtiz,NaN,$ 4374761,509.953,8.3
46,tt0064116,C'era una volta il West,1968-12-21,Western,165,Italy,PG-13,Sergio Leone,NaN,$ 112911,295.220,8.3
47,tt0095327,Hotaru no haka,2015-10-11,"Animation, Drama, War",89,Japan,NaN,Isao Takahata,NaN,$ 516962,225.438,8.3
48,tt0095765,Nuovo Cinema Paradiso,1988-11-17,Drama,155,Italy,NaN,Giuseppe Tornatore,NaN,$ 13826605,223.050,8.3
49,tt0027977,Modern Times,1937-03-12,"Comedy, Drama, Family",87,USA,G,Charles Chaplin,NaN,$ 457688,211.250,8.3
50,tt1345836,The Dark Knight Rises,2012-08-29,"Action, Adventure",164,UK,PG-13,Christopher Nolan,NaN,$ 1081133191,1.480.582,8.3
51,tt1853728,Django Unchained,2013-01-17,"Drama, Western",165,USA,R,Quentin Tarantino,NaN,$ 425368238,1.317.856,8.3
52,tt0209144,Memento,2001-01-19,"Mystery, Thriller",113,USA,R,Christopher Nolan,NaN,$ 39970386,1.098.879,8.2
53,tt0910970,WALLÂ·E,2008-10-17,"Animation, Adventure, Family",98,USA,G,Andrew Stanton,NaN,$ 521311860,974.734,8.2
54,tt0081505,The Shining,1980-12-22,"Drama, Horror",146,UK,R,Stanley Kubrick,NaN,$ 46520613,869.480,8.2
55,tt0082971,Raiders of the Lost Ark,1981-06-12,"Action, Adventure",115,USA,PG,Steven Spielberg,NaN,$ 390133212,865.510,8.2
56,tt4154756,Avengers: Infinity War,2018-04-25,"Action, Adventure, Sci-Fi",149,USA,NaN,"Anthony Russo, Joe Russo",NaN,$ 2048359754,796.486,8.2
57,tt0078748,Alien,1979-10-25,"Horror, Sci-Fi",117,UK,R,Ridley Scott,NaN,$ 108110316,768.874,8.2
58,tt4154796,Avengers: Endgame,2019-04-24,"Action, Adventure, Drama",181,USA,NaN,"Anthony Russo, Joe Russo",NaN,$ 2797800564,754.786,8.2
59,tt0078788,Apocalypse Now,1979-12-18,"Drama, Mystery, War",147,USA,R,Francis Ford Coppola,NaN,$ 91968688,591.251,8.2
60,tt0364569,Oldeuboi,2005-05-06,"Action, Drama, Mystery",120,South Korea,R,Chan-wook Park,NaN,$ 15002116,501.082,8.1
61,tt0057012,Dr. Strangelove or: How I Learned to Stop Worr...,1964-04-03,Comedy,95,UK,PG,Stanley Kubrick,NaN,$ 9443876,441.115,8.1
62,tt0047396,Rear Window,1955-04-14,"Mystery, Thriller",112,USA,NaN,Alfred Hitchcock,NaN,$ 37032034,432.390,8.1
63,tt2380307,Coco,2017-12-28,"Animation, Adventure, Family",105,USA,NaN,"Lee Unkrich, Adrian Molina",NaN,$ 807083670,352.455,8.1
64,tt0405094,Das Leben der Anderen,2007-04-06,"Drama, Mystery, Thriller",137,Germany,R,Florian Henckel von Donnersmarck,NaN,$ 77356942,349.642,8.1
65,tt4633694,Spider-Man: Into the Spider-Verse,2018-12-25,"Animation, Action, Adventure",117,USA,NaN,"Bob Persichetti, Peter Ramsey",NaN,$ 375540831,335.892,8.1
66,tt1187043,3 Idiots,2009-12-25,"Comedy, Drama",170,India,NaN,Rajkumar Hirani,NaN,$ 60262836,332.217,8.1
67,tt0119698,Mononoke-hime,2000-05-19,"Animation, Adventure, Fantasy",134,Japan,PG-13,Hayao Miyazaki,NaN,$ 169785629,331.045,8.0
68,tt0087843,Once Upon a Time in America,1984-09-28,"Crime, Drama",229,USA,R,Sergio Leone,NaN,$ 5472914,302.317,8.0
69,tt0032553,The Great Dictator,1945-06-25,"Comedy, Drama, War",125,USA,NaN,Charles Chaplin,NaN,$ 969879,197.381,8.0
70,tt0043014,Sunset Blvd.,"The 6th of marzo, year 1951","Drama, Film-Noir",110,USA,NaN,Billy Wilder,NaN,$ 299645,195.789,8.0
71,tt0361748,Inglourious Basterds,2009-10-02,"Adventure, Drama, War",153,Germany,R,Quentin Tarantino,NaN,$ 321455689,1.229.958,8.0
72,tt0169547,American Beauty,2000-01-21,Drama,122,USA,R,Sam Mendes,NaN,$ 356296601,1.049.009,8.0
73,tt0112573,Braveheart,1995-12-01,"Biography, Drama, History",178,USA,R,Mel Gibson,NaN,$ 213216216,941.683,7.9
74,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983-10-21,"Action, Adventure, Fantasy",131,USA,PG,Richard Marquand,NaN,$ 475347111,928.036,7.9
75,tt0105236,Reservoir Dogs,1992-10-09,"Crime, Drama, Thriller",99,USA,R,Quentin Tarantino,NaN,$ 2889963,896.551,7.9
76,tt0338013,Eternal Sunshine of the Spotless Mind,2004-10-22,"Drama, Romance, Sci-Fi",108,USA,R,Michel Gondry,NaN,$ 74036715,889.875,7.9
77,tt0114709,Toy Story,1996-03-22,"Animation, Adventure, Comedy",81,USA,G,John Lasseter,NaN,$ 404265438,864.461,7.9
78,tt0119217,Good Will Hunting,1998-03-06,"Drama, Romance",126,USA,R,Gus Van Sant,NaN,$ 225933435,837.379,7.8
79,tt0208092,Snatch,2001-03-16,"Comedy, Crime",104,UK,R,Guy Ritchie,NaN,$ 83557872,766.589,7.8
80,tt0180093,Requiem for a Dream,2000-12-15,Drama,102,USA,R,Darren Aronofsky,NaN,$ 7390108,748.291,7.8
81,tt0066921,A Clockwork Orange,1972-09-07,"Crime, Drama, Sci-Fi",136,UK,NaN,Stanley Kubrick,NaN,$ 26903440,740.301,7.8
82,tt0435761,Toy Story 3,2010-07-07,"Animation, Adventure, Comedy",103,USA,G,Lee Unkrich,NaN,$ 1066969703,739.717,7.8
83,tt0086250,Scarface,1984-02-34,"Crime, Drama",170,USA,R,Brian De Palma,NaN,$ 66023585,721.343,7.8
84,tt0075314,Taxi Driver,1976-13-24,"Crime, Drama",114,USA,R,Martin Scorsese,NaN,$ 28441292,703.264,7.7
85,tt0211915,Le fabuleux destin d'AmÃ©lie Poulain,2002-01-25,"Comedy, Romance",122,France,R,Jean-Pierre Jeunet,NaN,$ 173924742,690.480,7.7
86,tt0093058,Full Metal Jacket,1987-10-09,"Drama, War",116,UK,NaN,Stanley Kubrick,NaN,$ 46357676,658.175,7.7
87,tt0090605,Aliens,1986-09-24,"Action, Adventure, Sci-Fi",137,USA,R,James Cameron,NaN,$ 131384634,639.500,7.7
88,tt0062622,2001: A Space Odyssey,1968-12-12,"Adventure, Sci-Fi",149,UK,G,Stanley Kubrick,NaN,$ 68989547,587.866,7.6
89,tt0033467,Citizen Kane,1948-11-25,"Drama, Mystery",119,USA,NaN,Orson Welles,NaN,$ 1594107,389.322,7.6
90,tt8579674,1917,2020-01-23,"Drama, War",119,USA,NaN,Sam Mendes,NaN,$ 384857224,362.897,7.6
91,tt0086879,Amadeus,1985-02-15,"Biography, Drama, History",160,USA,R,Milos Forman,NaN,$ 52066791,361.028,7.6
92,tt0052357,Vertigo,1958-11-18,"Mystery, Romance, Thriller",128,USA,NaN,Alfred Hitchcock,NaN,$ 7796389,352.786,7.5
93,tt0053125,North by Northwest,1959-10-28,"Adventure, Mystery, Thriller",136,USA,NaN,Alfred Hitchcock,NaN,$ 73446,291.628,7.5
94,tt2106476,Jagten,2012-11-22,Drama,115,Denmark,R,Thomas Vinterberg,NaN,$ 15843274,269.616,7.5
95,tt0056172,Lawrence of Arabia,1963-10-29,"Adventure, Biography, Drama",228,UK,PG,David Lean,NaN,$ 45710874,261.504,7.5
96,tt0070735,The Sting,1974-03-21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,NaN,$ 156000000,236.285,7.5
97,tt0082096,Das Boot,1982-03-18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,NaN,$ 11487676,226.427,7.5
98,tt0059578,Per qualche dollaro in piÃ¹,1965-12-20,Western,132,Italy,NaN,Sergio Leone,NaN,$ 15000000,226.039,7.4
99,tt1832382,Jodaeiye Nader az Simin,2011-10-21,Drama,123,Iran,PG-13,Asghar Farhadi,NaN,$ 22926076,214.165,7.4
100,tt0045152,Singin' in the Rain,1953-02-05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,NaN,$ 1864182,213.152,7.4

In [47]:
df = df.drop('Unnamed: 8', axis=1)

In [48]:
df.columns = df.columns.str.replace(r'[^\x00-\x7F]+', '', regex=True)

In [49]:
df.head(5)

,IMBD title ID,Original titl,Release year,Genr,Duration,Country,Content Rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"

In [50]:
df.rename(columns={'Genr': 'Genre', 'Original titl': 'Original Title'}, inplace=True)

In [102]:
df.columns = df.columns.str.strip()

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IMBD title ID   100 non-null    object
 1   Original Title  100 non-null    object
 2   Release year    100 non-null    object
 3   Genre           100 non-null    object
 4   Duration        99 non-null     object
 5   Country         100 non-null    object
 6   Content Rating  77 non-null     object
 7   Director        100 non-null    object
 8   Income          100 non-null    object
 9   Votes           100 non-null    object
 10  Score           100 non-null    object
dtypes: object(11)
memory usage: 8.8+ KB

In [53]:
df['Release year'] = pd.to_datetime(df['Release year'], errors='coerce')

In [55]:
df[['Original Title']]

                                        Original Title
0                             The Shawshank Redemption
1                                        The Godfather
2                                      The Dark Knight
3                               The Godfather: Part II
4                                         Pulp Fiction
5        The Lord of the Rings: The Return of the King
6                                     Schindler's List
7                                         12 Angry Men
8                                            Inception
9                                           Fight Club
10                                        Forrest Gump
11   The Lord of the Rings: The Fellowship of the Ring
12                     Il buono, il brutto, il cattivo
13                                                 NaN
14                                          The Matrix
15               The Lord of the Rings: The Two Towers
16      Star Wars: Episode V - The Empire Strikes Back
17                                          Goodfellas
18                     One Flew Over the Cuckoo's Nest
19                                        Interstellar
20                                               Se7en
21                            The Silence of the Lambs
22                                           Star Wars
23                                 Saving Private Ryan
24                                      The Green Mile
25                                      Cidade de Deus
26                       Sen to Chihiro no kamikakushi
27                                    La vita B9 bella
28                                        Gisaengchung
29                               It's a Wonderful Life
30                                Shichinin no samurai
31                                           Gladiator
32                                        The Departed
33                                        The Prestige
34                                  Back to the Future
35                                  American History X
36                                               LÃ©on
37                          Terminator 2: Judgment Day
38                                  The Usual Suspects
39                                       The Lion King
40                                               Joker
41                                        Intouchables
42                                         The Pianist
43                                            Whiplash
44                                              Psycho
45                                          Casablanca
46                             C'era una volta il West
47                                      Hotaru no haka
48                               Nuovo Cinema Paradiso
49                                        Modern Times
50                               The Dark Knight Rises
51                                    Django Unchained
52                                             Memento
53                                             WALLÂ·E
54                                         The Shining
55                             Raiders of the Lost Ark
56                              Avengers: Infinity War
57                                               Alien
58                                   Avengers: Endgame
59                                      Apocalypse Now
60                                            Oldeuboi
61   Dr. Strangelove or: How I Learned to Stop Worr...
62                                         Rear Window
63                                                Coco
64                               Das Leben der Anderen
65                   Spider-Man: Into the Spider-Verse
66                                            3 Idiots
67                                       Mononoke-hime
68                         Once Upon a Time in America
69                                  The Great Dictator
70                                        Sunset Blvd.
71                                Inglourious Basterds
72                                     American Beauty
73                                          Braveheart
74          Star Wars: Episode VI - Return of the Jedi
75                                      Reservoir Dogs
76               Eternal Sunshine of the Spotless Mind
77                                           Toy Story
78                                   Good Will Hunting
79                                              Snatch
80                                 Requiem for a Dream
81                                  A Clockwork Orange
82                                         Toy Story 3
83                                            Scarface
84                                         Taxi Driver
85                Le fabuleux destin d'AmÃ©lie Poulain
86                                   Full Metal Jacket
87                                              Aliens
88                               2001: A Space Odyssey
89                                        Citizen Kane
90                                                1917
91                                             Amadeus
92                                             Vertigo
93                                  North by Northwest
94                                              Jagten
95                                  Lawrence of Arabia
96                                           The Sting
97                                            Das Boot
98                         Per qualche dollaro in piÃ¹
99                             Jodaeiye Nader az Simin
100                                Singin' in the Rain

In [56]:
df['Original Title'] = (df['Original Title']
    .str.encode('latin1', errors='ignore')
    .str.decode('utf-8', errors='ignore')
    .str.strip()
)

In [42]:
df[['Original Title']]

                                        Original Title
0                             The Shawshank Redemption
1                                        The Godfather
2                                      The Dark Knight
3                               The Godfather: Part II
4                                         Pulp Fiction
5        The Lord of the Rings: The Return of the King
6                                     Schindler's List
7                                         12 Angry Men
8                                            Inception
9                                           Fight Club
10                                        Forrest Gump
11   The Lord of the Rings: The Fellowship of the Ring
12                     Il buono, il brutto, il cattivo
13                                                 nan
14                                          The Matrix
15               The Lord of the Rings: The Two Towers
16      Star Wars: Episode V - The Empire Strikes Back
17                                          Goodfellas
18                     One Flew Over the Cuckoo's Nest
19                                        Interstellar
20                                               Se7en
21                            The Silence of the Lambs
22                                           Star Wars
23                                 Saving Private Ryan
24                                      The Green Mile
25                                      Cidade de Deus
26                       Sen to Chihiro no kamikakushi
27                                    La vita B9 bella
28                                        Gisaengchung
29                               It's a Wonderful Life
30                                Shichinin no samurai
31                                           Gladiator
32                                        The Departed
33                                        The Prestige
34                                  Back to the Future
35                                  American History X
36                                                 Lon
37                          Terminator 2: Judgment Day
38                                  The Usual Suspects
39                                       The Lion King
40                                               Joker
41                                        Intouchables
42                                         The Pianist
43                                            Whiplash
44                                              Psycho
45                                          Casablanca
46                             C'era una volta il West
47                                      Hotaru no haka
48                               Nuovo Cinema Paradiso
49                                        Modern Times
50                               The Dark Knight Rises
51                                    Django Unchained
52                                             Memento
53                                               WALLE
54                                         The Shining
55                             Raiders of the Lost Ark
56                              Avengers: Infinity War
57                                               Alien
58                                   Avengers: Endgame
59                                      Apocalypse Now
60                                            Oldeuboi
61   Dr. Strangelove or: How I Learned to Stop Worr...
62                                         Rear Window
63                                                Coco
64                               Das Leben der Anderen
65                   Spider-Man: Into the Spider-Verse
66                                            3 Idiots
67                                       Mononoke-hime
68                         Once Upon a Time in America
69                                  The Great Dictator
70                                        Sunset Blvd.
71                                Inglourious Basterds
72                                     American Beauty
73                                          Braveheart
74          Star Wars: Episode VI - Return of the Jedi
75                                      Reservoir Dogs
76               Eternal Sunshine of the Spotless Mind
77                                           Toy Story
78                                   Good Will Hunting
79                                              Snatch
80                                 Requiem for a Dream
81                                  A Clockwork Orange
82                                         Toy Story 3
83                                            Scarface
84                                         Taxi Driver
85                  Le fabuleux destin d'Amlie Poulain
86                                   Full Metal Jacket
87                                              Aliens
88                               2001: A Space Odyssey
89                                        Citizen Kane
90                                                1917
91                                             Amadeus
92                                             Vertigo
93                                  North by Northwest
94                                              Jagten
95                                  Lawrence of Arabia
96                                           The Sting
97                                            Das Boot
98                           Per qualche dollaro in pi
99                             Jodaeiye Nader az Simin
100                                Singin' in the Rain

In [57]:
df[['Release year']]

    Release year
0     1995-02-10
1            NaT
2            NaT
3     1975-09-25
4     1994-10-28
5            NaT
6     1994-03-11
7     1957-09-04
8     2010-09-24
9            NaT
10    1994-10-06
11    2002-01-18
12           NaT
13           NaT
14    1999-05-07
15           NaT
16    1980-09-19
17    1990-09-20
18           NaT
19    2014-11-06
20    1995-12-15
21    1991-03-05
22    1977-10-20
23    1998-10-30
24    2000-10-03
25    2003-05-09
26    2003-04-18
27    1997-12-20
28    2019-11-07
29    1948-03-11
30    1955-08-19
31    2000-05-19
32    2006-10-27
33    2006-12-22
34    1985-10-18
35    1999-08-27
36    1995-04-07
37    1991-12-19
38    1995-11-30
39    1994-11-25
40    2019-10-03
41    2012-02-24
42    2002-10-25
43    2015-02-12
44    1960-10-28
45           NaT
46    1968-12-21
47    2015-10-11
48    1988-11-17
49    1937-03-12
50    2012-08-29
51    2013-01-17
52    2001-01-19
53    2008-10-17
54    1980-12-22
55    1981-06-12
56    2018-04-25
57    1979-10-25
58    2019-04-24
59    1979-12-18
60    2005-05-06
61    1964-04-03
62    1955-04-14
63    2017-12-28
64    2007-04-06
65    2018-12-25
66    2009-12-25
67    2000-05-19
68    1984-09-28
69    1945-06-25
70           NaT
71    2009-10-02
72    2000-01-21
73    1995-12-01
74    1983-10-21
75    1992-10-09
76    2004-10-22
77    1996-03-22
78    1998-03-06
79    2001-03-16
80    2000-12-15
81    1972-09-07
82    2010-07-07
83           NaT
84           NaT
85    2002-01-25
86    1987-10-09
87    1986-09-24
88    1968-12-12
89    1948-11-25
90    2020-01-23
91    1985-02-15
92    1958-11-18
93    1959-10-28
94    2012-11-22
95    1963-10-29
96    1974-03-21
97    1982-03-18
98    1965-12-20
99    2011-10-21
100   1953-02-05

In [60]:
df[['Duration']]

           Duration
0               142
1               175
2               152
3               220
4
5               201
6               Nan
7                96
8               148
9               Inf
10              142
11             178c
12              161
13              NaN
14              NaN
15              179
16   Not Applicable
17              146
18                -
19              169
20              127
21              118
22              121
23              169
24              189
25              130
26              125
27              116
28              132
29              130
30              207
31              155
32              151
33              130
34              116
35              119
36              110
37              137
38              106
39               88
40              122
41              112
42              150
43              106
44              109
45              102
46              165
47               89
48              155
49               87
50              164
51              165
52              113
53               98
54              146
55              115
56              149
57              117
58              181
59              147
60              120
61               95
62              112
63              105
64              137
65              117
66              170
67              134
68              229
69              125
70              110
71              153
72              122
73              178
74              131
75               99
76              108
77               81
78              126
79              104
80              102
81              136
82              103
83              170
84              114
85              122
86              116
87              137
88              149
89              119
90              119
91              160
92              128
93              136
94              115
95              228
96              129
97              149
98              132
99              123
100             103

In [62]:
df['Duration'] = df['Duration'].str.replace(r'[^0-9]', '', regex=True)

In [67]:
df['Duration'] = df['Duration'].fillna(0).replace('', 0)

In [69]:
df['Duration'] = df['Duration'].astype(int)

In [70]:
df[['Duration']]

     Duration
0         142
1         175
2         152
3         220
4           0
5         201
6           0
7          96
8         148
9           0
10        142
11        178
12        161
13          0
14          0
15        179
16          0
17        146
18          0
19        169
20        127
21        118
22        121
23        169
24        189
25        130
26        125
27        116
28        132
29        130
30        207
31        155
32        151
33        130
34        116
35        119
36        110
37        137
38        106
39         88
40        122
41        112
42        150
43        106
44        109
45        102
46        165
47         89
48        155
49         87
50        164
51        165
52        113
53         98
54        146
55        115
56        149
57        117
58        181
59        147
60        120
61         95
62        112
63        105
64        137
65        117
66        170
67        134
68        229
69        125
70        110
71        153
72        122
73        178
74        131
75         99
76        108
77         81
78        126
79        104
80        102
81        136
82        103
83        170
84        114
85        122
86        116
87        137
88        149
89        119
90        119
91        160
92        128
93        136
94        115
95        228
96        129
97        149
98        132
99        123
100       103

In [71]:
df['Country'].value_counts(dropna=False)

Country
USA             62
UK              12
Italy            4
Japan            4
France           3
Germany          2
South Korea      2
Italy1           1
West Germany     1
Denmark          1
India            1
Brazil           1
US               1
US.              1
New Zeland       1
NaN              1
New Zesland      1
New Zealand      1
Iran             1
Name: count, dtype: int64

In [72]:
df['Country'] = df['Country'].replace({'US': 'USA'})

In [73]:
df['Country'] = df['Country'].str.replace(r'[\.0-9].*$', '', regex=True)

In [75]:
df['Country'] = df['Country'].astype(str)
unique_countries = df['Country'].unique()
correct_name = 'New Zealand'
for name in unique_countries:
    if get_close_matches(name, [correct_name], cutoff=0.6):
        df['Country'] = df['Country'].replace(name, correct_name)

In [79]:
df['Country'] = df['Country'].replace('nan', '')

In [80]:
df['Country'].value_counts(dropna=False)

Country
USA             63
UK              12
Italy            5
Japan            4
New Zealand      3
France           3
South Korea      2
Germany          2
                 1
US               1
Brazil           1
India            1
Denmark          1
West Germany     1
Iran             1
Name: count, dtype: int64

In [82]:
df['Content Rating'].value_counts(dropna=False)

Content Rating
R            45
NaN          24
PG-13        12
PG           11
G             6
Not Rated     1
Approved      1
Unrated       1
Name: count, dtype: int64

In [84]:
df['Content Rating'] = df['Content Rating'].fillna('Not Rated')

In [85]:
df['Content Rating'].value_counts(dropna=False)

Content Rating
R            45
Not Rated    25
PG-13        12
PG           11
G             6
Approved      1
Unrated       1
Name: count, dtype: int64

In [86]:
df[['Director']]

                             Director
0                      Frank Darabont
1                Francis Ford Coppola
2                   Christopher Nolan
3                Francis Ford Coppola
4                   Quentin Tarantino
5                       Peter Jackson
6                    Steven Spielberg
7                        Sidney Lumet
8                   Christopher Nolan
9                       David Fincher
10                    Robert Zemeckis
11                      Peter Jackson
12                       Sergio Leone
13                                NaN
14    Lana Wachowski, Lilly Wachowski
15                      Peter Jackson
16                     Irvin Kershner
17                    Martin Scorsese
18                       Milos Forman
19                  Christopher Nolan
20                      David Fincher
21                     Jonathan Demme
22                       George Lucas
23                   Steven Spielberg
24                     Frank Darabont
25    Fernando Meirelles, KÃ¡tia Lund
26                     Hayao Miyazaki
27                    Roberto Benigni
28                       Bong Joon Ho
29                        Frank Capra
30                     Akira Kurosawa
31                       Ridley Scott
32                    Martin Scorsese
33                  Christopher Nolan
34                    Robert Zemeckis
35                          Tony Kaye
36                         Luc Besson
37                      James Cameron
38                       Bryan Singer
39          Roger Allers, Rob Minkoff
40                      Todd Phillips
41    Olivier Nakache, Ãric Toledano
42                     Roman Polanski
43                    Damien Chazelle
44                   Alfred Hitchcock
45                     Michael Curtiz
46                       Sergio Leone
47                      Isao Takahata
48                 Giuseppe Tornatore
49                    Charles Chaplin
50                  Christopher Nolan
51                  Quentin Tarantino
52                  Christopher Nolan
53                     Andrew Stanton
54                    Stanley Kubrick
55                   Steven Spielberg
56           Anthony Russo, Joe Russo
57                       Ridley Scott
58           Anthony Russo, Joe Russo
59               Francis Ford Coppola
60                     Chan-wook Park
61                    Stanley Kubrick
62                   Alfred Hitchcock
63         Lee Unkrich, Adrian Molina
64   Florian Henckel von Donnersmarck
65      Bob Persichetti, Peter Ramsey
66                    Rajkumar Hirani
67                     Hayao Miyazaki
68                       Sergio Leone
69                    Charles Chaplin
70                       Billy Wilder
71                  Quentin Tarantino
72                         Sam Mendes
73                         Mel Gibson
74                   Richard Marquand
75                  Quentin Tarantino
76                      Michel Gondry
77                      John Lasseter
78                       Gus Van Sant
79                        Guy Ritchie
80                   Darren Aronofsky
81                    Stanley Kubrick
82                        Lee Unkrich
83                     Brian De Palma
84                    Martin Scorsese
85                 Jean-Pierre Jeunet
86                    Stanley Kubrick
87                      James Cameron
88                    Stanley Kubrick
89                       Orson Welles
90                         Sam Mendes
91                       Milos Forman
92                   Alfred Hitchcock
93                   Alfred Hitchcock
94                  Thomas Vinterberg
95                         David Lean
96                    George Roy Hill
97                  Wolfgang Petersen
98                       Sergio Leone
99                     Asghar Farhadi
100                     Stanley Donen

In [87]:
df['Director'] = df['Director'].str.encode('latin1').str.decode('utf-8', errors='ignore')

In [88]:
df['Director'] = df['Director'].fillna('')

In [89]:
df[['Director']]

                             Director
0                      Frank Darabont
1                Francis Ford Coppola
2                   Christopher Nolan
3                Francis Ford Coppola
4                   Quentin Tarantino
5                       Peter Jackson
6                    Steven Spielberg
7                        Sidney Lumet
8                   Christopher Nolan
9                       David Fincher
10                    Robert Zemeckis
11                      Peter Jackson
12                       Sergio Leone
13
14    Lana Wachowski, Lilly Wachowski
15                      Peter Jackson
16                     Irvin Kershner
17                    Martin Scorsese
18                       Milos Forman
19                  Christopher Nolan
20                      David Fincher
21                     Jonathan Demme
22                       George Lucas
23                   Steven Spielberg
24                     Frank Darabont
25     Fernando Meirelles, Kátia Lund
26                     Hayao Miyazaki
27                    Roberto Benigni
28                       Bong Joon Ho
29                        Frank Capra
30                     Akira Kurosawa
31                       Ridley Scott
32                    Martin Scorsese
33                  Christopher Nolan
34                    Robert Zemeckis
35                          Tony Kaye
36                         Luc Besson
37                      James Cameron
38                       Bryan Singer
39          Roger Allers, Rob Minkoff
40                      Todd Phillips
41     Olivier Nakache, Éric Toledano
42                     Roman Polanski
43                    Damien Chazelle
44                   Alfred Hitchcock
45                     Michael Curtiz
46                       Sergio Leone
47                      Isao Takahata
48                 Giuseppe Tornatore
49                    Charles Chaplin
50                  Christopher Nolan
51                  Quentin Tarantino
52                  Christopher Nolan
53                     Andrew Stanton
54                    Stanley Kubrick
55                   Steven Spielberg
56           Anthony Russo, Joe Russo
57                       Ridley Scott
58           Anthony Russo, Joe Russo
59               Francis Ford Coppola
60                     Chan-wook Park
61                    Stanley Kubrick
62                   Alfred Hitchcock
63         Lee Unkrich, Adrian Molina
64   Florian Henckel von Donnersmarck
65      Bob Persichetti, Peter Ramsey
66                    Rajkumar Hirani
67                     Hayao Miyazaki
68                       Sergio Leone
69                    Charles Chaplin
70                       Billy Wilder
71                  Quentin Tarantino
72                         Sam Mendes
73                         Mel Gibson
74                   Richard Marquand
75                  Quentin Tarantino
76                      Michel Gondry
77                      John Lasseter
78                       Gus Van Sant
79                        Guy Ritchie
80                   Darren Aronofsky
81                    Stanley Kubrick
82                        Lee Unkrich
83                     Brian De Palma
84                    Martin Scorsese
85                 Jean-Pierre Jeunet
86                    Stanley Kubrick
87                      James Cameron
88                    Stanley Kubrick
89                       Orson Welles
90                         Sam Mendes
91                       Milos Forman
92                   Alfred Hitchcock
93                   Alfred Hitchcock
94                  Thomas Vinterberg
95                         David Lean
96                    George Roy Hill
97                  Wolfgang Petersen
98                       Sergio Leone
99                     Asghar Farhadi
100                     Stanley Donen

In [90]:
df[['Income']]

            Income
0       $ 28815245
1      $ 246120974
2     $ 1005455211
3    $ 4o8,035,783
4      $ 222831817
5     $ 1142271098
6      $ 322287794
7            $ 576
8      $ 869784991
9      $ 101218804
10     $ 678229452
11     $ 887934303
12      $ 25252481
13             NaN
14     $ 465718588
15     $ 951227416
16     $ 549265501
17      $ 46879633
18     $ 108997629
19     $ 696742056
20     $ 327333559
21     $ 272753884
22     $ 775768912
23     $ 482349603
24     $ 286801374
25      $ 30680793
26     $ 355467056
27     $ 230098753
28     $ 257604912
29       $ 6130720
30        $ 322773
31     $ 465361176
32     $ 291465034
33     $ 109676311
34     $ 388774684
35      $ 23875127
36      $ 19552639
37     $ 520884847
38      $ 23341568
39     $ 968511805
40    $ 1074251311
41     $ 426588510
42     $ 120072577
43      $ 48983260
44      $ 32008644
45       $ 4374761
46        $ 112911
47        $ 516962
48      $ 13826605
49        $ 457688
50    $ 1081133191
51     $ 425368238
52      $ 39970386
53     $ 521311860
54      $ 46520613
55     $ 390133212
56    $ 2048359754
57     $ 108110316
58    $ 2797800564
59      $ 91968688
60      $ 15002116
61       $ 9443876
62      $ 37032034
63     $ 807083670
64      $ 77356942
65     $ 375540831
66      $ 60262836
67     $ 169785629
68       $ 5472914
69        $ 969879
70        $ 299645
71     $ 321455689
72     $ 356296601
73     $ 213216216
74     $ 475347111
75       $ 2889963
76      $ 74036715
77     $ 404265438
78     $ 225933435
79      $ 83557872
80       $ 7390108
81      $ 26903440
82    $ 1066969703
83      $ 66023585
84      $ 28441292
85     $ 173924742
86      $ 46357676
87     $ 131384634
88      $ 68989547
89       $ 1594107
90     $ 384857224
91      $ 52066791
92       $ 7796389
93         $ 73446
94      $ 15843274
95      $ 45710874
96     $ 156000000
97      $ 11487676
98      $ 15000000
99      $ 22926076
100      $ 1864182

In [91]:
df['Income'] = (df['Income']
    .astype(str)
    .str.replace('o', '0')
    .str.replace(r'[^0-9]', '', regex=True)
    .replace('', '0')
    .astype(float)
    .div(10)
    .astype(int)
)

In [92]:
df[['Income']]

        Income
0      2881524
1     24612097
2    100545521
3     40803578
4     22283181
5    114227109
6     32228779
7           57
8     86978499
9     10121880
10    67822945
11    88793430
12     2525248
13           0
14    46571858
15    95122741
16    54926550
17     4687963
18    10899762
19    69674205
20    32733355
21    27275388
22    77576891
23    48234960
24    28680137
25     3068079
26    35546705
27    23009875
28    25760491
29      613072
30       32277
31    46536117
32    29146503
33    10967631
34    38877468
35     2387512
36     1955263
37    52088484
38     2334156
39    96851180
40   107425131
41    42658851
42    12007257
43     4898326
44     3200864
45      437476
46       11291
47       51696
48     1382660
49       45768
50   108113319
51    42536823
52     3997038
53    52131186
54     4652061
55    39013321
56   204835975
57    10811031
58   279780056
59     9196868
60     1500211
61      944387
62     3703203
63    80708367
64     7735694
65    37554083
66     6026283
67    16978562
68      547291
69       96987
70       29964
71    32145568
72    35629660
73    21321621
74    47534711
75      288996
76     7403671
77    40426543
78    22593343
79     8355787
80      739010
81     2690344
82   106696970
83     6602358
84     2844129
85    17392474
86     4635767
87    13138463
88     6898954
89      159410
90    38485722
91     5206679
92      779638
93        7344
94     1584327
95     4571087
96    15600000
97     1148767
98     1500000
99     2292607
100     186418

In [93]:
df[['Votes']]

         Votes
0    2.278.845
1    1.572.674
2    2.241.615
3    1.098.714
4    1.780.147
5    1.604.280
6    1.183.248
7      668.473
8    2.002.816
9    1.807.440
10   1.755.490
11   1.619.920
12     672.499
13         NaN
14   1.632.315
15   1.449.778
16   1.132.073
17     991.505
18     891.071
19   1.449.256
20   1.402.015
21   1.234.134
22   1.204.107
23   1.203.825
24   1.112.336
25     685.856
26     626.693
27     605.648
28     470.931
29     388.310
30     307.958
31   1.308.193
32   1.159.703
33   1.155.723
34   1.027.330
35   1.014.218
36   1.007.598
37     974.970
38     968.947
39     917.248
40     855.097
41     736.691
42     707.942
43     690.732
44     586.765
45     509.953
46     295.220
47     225.438
48     223.050
49     211.250
50   1.480.582
51   1.317.856
52   1.098.879
53     974.734
54     869.480
55     865.510
56     796.486
57     768.874
58     754.786
59     591.251
60     501.082
61     441.115
62     432.390
63     352.455
64     349.642
65     335.892
66     332.217
67     331.045
68     302.317
69     197.381
70     195.789
71   1.229.958
72   1.049.009
73     941.683
74     928.036
75     896.551
76     889.875
77     864.461
78     837.379
79     766.589
80     748.291
81     740.301
82     739.717
83     721.343
84     703.264
85     690.480
86     658.175
87     639.500
88     587.866
89     389.322
90     362.897
91     361.028
92     352.786
93     291.628
94     269.616
95     261.504
96     236.285
97     226.427
98     226.039
99     214.165
100    213.152

In [103]:
df['Votes'] = df['Votes'].fillna(0)

In [104]:
df['Votes'] = df['Votes'].astype(str).str.replace('.', '', regex=False).astype(int)

In [105]:
df[['Votes']]

       Votes
0    2278845
1    1572674
2    2241615
3    1098714
4    1780147
5    1604280
6    1183248
7     668473
8    2002816
9    1807440
10   1755490
11   1619920
12    672499
13         0
14   1632315
15   1449778
16   1132073
17    991505
18    891071
19   1449256
20   1402015
21   1234134
22   1204107
23   1203825
24   1112336
25    685856
26    626693
27    605648
28    470931
29    388310
30    307958
31   1308193
32   1159703
33   1155723
34   1027330
35   1014218
36   1007598
37    974970
38    968947
39    917248
40    855097
41    736691
42    707942
43    690732
44    586765
45    509953
46    295220
47    225438
48    223050
49    211250
50   1480582
51   1317856
52   1098879
53    974734
54    869480
55    865510
56    796486
57    768874
58    754786
59    591251
60    501082
61    441115
62    432390
63    352455
64    349642
65    335892
66    332217
67    331045
68    302317
69    197381
70    195789
71   1229958
72   1049009
73    941683
74    928036
75    896551
76    889875
77    864461
78    837379
79    766589
80    748291
81    740301
82    739717
83    721343
84    703264
85    690480
86    658175
87    639500
88    587866
89    389322
90    362897
91    361028
92    352786
93    291628
94    269616
95    261504
96    236285
97    226427
98    226039
99    214165
100   213152

In [106]:
df[['Votes']]

       Votes
0    2278845
1    1572674
2    2241615
3    1098714
4    1780147
5    1604280
6    1183248
7     668473
8    2002816
9    1807440
10   1755490
11   1619920
12    672499
13         0
14   1632315
15   1449778
16   1132073
17    991505
18    891071
19   1449256
20   1402015
21   1234134
22   1204107
23   1203825
24   1112336
25    685856
26    626693
27    605648
28    470931
29    388310
30    307958
31   1308193
32   1159703
33   1155723
34   1027330
35   1014218
36   1007598
37    974970
38    968947
39    917248
40    855097
41    736691
42    707942
43    690732
44    586765
45    509953
46    295220
47    225438
48    223050
49    211250
50   1480582
51   1317856
52   1098879
53    974734
54    869480
55    865510
56    796486
57    768874
58    754786
59    591251
60    501082
61    441115
62    432390
63    352455
64    349642
65    335892
66    332217
67    331045
68    302317
69    197381
70    195789
71   1229958
72   1049009
73    941683
74    928036
75    896551
76    889875
77    864461
78    837379
79    766589
80    748291
81    740301
82    739717
83    721343
84    703264
85    690480
86    658175
87    639500
88    587866
89    389322
90    362897
91    361028
92    352786
93    291628
94    269616
95    261504
96    236285
97    226427
98    226039
99    214165
100   213152

In [107]:
df[['Score']]

      Score
0       9.3
1       9.2
2        9.
3      9,.0
4      8,9f
5      08.9
6       8.9
7       8.9
8      8..8
9       8.8
10      8:8
11      8.8
12      8.8
13      NaN
14    ++8.7
15     8.7.
16   8,7e-0
17      8.7
18      8.7
19      8.6
20      8.6
21      8,6
22      8.6
23      8.6
24      8.6
25      8.6
26      8.6
27      8.6
28      8.6
29      8.6
30      8.6
31      8.5
32      8.5
33      8.5
34      8.5
35      8.5
36      8.5
37      8.4
38      8.4
39      8.4
40      8.4
41      8.4
42      8.4
43      8.4
44      8.3
45      8.3
46      8.3
47      8.3
48      8.3
49      8.3
50      8.3
51      8.3
52      8.2
53      8.2
54      8.2
55      8.2
56      8.2
57      8.2
58      8.2
59      8.2
60      8.1
61      8.1
62      8.1
63      8.1
64      8.1
65      8.1
66      8.1
67      8.0
68      8.0
69      8.0
70      8.0
71      8.0
72      8.0
73      7.9
74      7.9
75      7.9
76      7.9
77      7.9
78      7.8
79      7.8
80      7.8
81      7.8
82      7.8
83      7.8
84      7.7
85      7.7
86      7.7
87      7.7
88      7.6
89      7.6
90      7.6
91      7.6
92      7.5
93      7.5
94      7.5
95      7.5
96      7.5
97      7.5
98      7.4
99      7.4
100     7.4

In [108]:
df['Score'] = pd.to_numeric(
    df['Score'].astype(str)
    .str.replace(r'[^0-9.,]', '', regex=True)
    .str.replace(',', '.')
    .str.replace(':', '.')
    .str.replace(r'\.+', '.', regex=True)
    .str.replace(r'^0+(?=\d)', '', regex=True)
    .str.strip('.'),
    errors='coerce'
)

In [109]:
df['Score'] = df['Score'].astype(str).str.extract(r'(\d\.\d)')[0]

In [110]:
df['Score'] = df['Score'].fillna(0)

In [112]:
df['Score'] = df['Score'].astype(float)

In [113]:
df[['Score']]

     Score
0      9.3
1      9.2
2      9.0
3      9.0
4      8.9
5      8.9
6      8.9
7      8.9
8      8.8
9      8.8
10     8.0
11     8.8
12     8.8
13     0.0
14     8.7
15     8.7
16     8.7
17     8.7
18     8.7
19     8.6
20     8.6
21     8.6
22     8.6
23     8.6
24     8.6
25     8.6
26     8.6
27     8.6
28     8.6
29     8.6
30     8.6
31     8.5
32     8.5
33     8.5
34     8.5
35     8.5
36     8.5
37     8.4
38     8.4
39     8.4
40     8.4
41     8.4
42     8.4
43     8.4
44     8.3
45     8.3
46     8.3
47     8.3
48     8.3
49     8.3
50     8.3
51     8.3
52     8.2
53     8.2
54     8.2
55     8.2
56     8.2
57     8.2
58     8.2
59     8.2
60     8.1
61     8.1
62     8.1
63     8.1
64     8.1
65     8.1
66     8.1
67     8.0
68     8.0
69     8.0
70     8.0
71     8.0
72     8.0
73     7.9
74     7.9
75     7.9
76     7.9
77     7.9
78     7.8
79     7.8
80     7.8
81     7.8
82     7.8
83     7.8
84     7.7
85     7.7
86     7.7
87     7.7
88     7.6
89     7.6
90     7.6
91     7.6
92     7.5
93     7.5
94     7.5
95     7.5
96     7.5
97     7.5
98     7.4
99     7.4
100    7.4